FROM python:3.9-slim

WORKDIR /app

COPY requirements-nginx-exporter.txt .
RUN pip install --no-cache-dir -r requirements-nginx-exporter.txt

COPY nginx-exporter.py .

EXPOSE 9113

CMD ["python", "nginx-exporter.py"]
