---
- name: Create etcd user
  user:
    name: etcd
    system: yes
    shell: /bin/false
    home: /var/lib/etcd
    create_home: yes

- name: Download etcd
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.5.9/etcd-v3.5.9-linux-amd64.tar.gz
    dest: /tmp/etcd-v3.5.9-linux-amd64.tar.gz
    mode: '0644'

- name: Extract etcd
  unarchive:
    src: /tmp/etcd-v3.5.9-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install etcd binaries
  copy:
    src: /tmp/etcd-v3.5.9-linux-amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  loop:
    - etcd
    - etcdctl

- name: Create etcd data directory
  file:
    path: /var/lib/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'

- name: Create etcd configuration directory
  file:
    path: /etc/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'

- name: Generate etcd configuration
  template:
    src: etcd.conf.yml.j2
    dest: /etc/etcd/etcd.conf.yml
    owner: etcd
    group: etcd
    mode: '0644'
  notify: restart etcd

- name: Create etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart etcd

- name: Enable and start etcd service
  systemd:
    name: etcd
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for etcd to be ready
  uri:
    url: "http://{{ private_ip }}:2379/health"
    method: GET
  register: etcd_health
  until: etcd_health.status == 200
  retries: 30
  delay: 5